# Generated by Django 4.2.2 on 2023-06-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='college',
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='self_introducing',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='education',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='EduVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='edu_verification/')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
