# Generated by Django 4.2.2 on 2023-07-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_tag_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
    ]
