# Generated by Django 4.2.2 on 2023-06-25 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField(null=True)),
                ('career', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('location', models.TextField(default='', max_length=200)),
                ('menu', models.TextField(default='', max_length=200)),
                ('area', models.TextField(default='', max_length=200)),
                ('avg_mothly_sales', models.TextField(default='', max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_profile',
            },
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('birth', models.DateField(null=True)),
                ('education', models.TextField(default='', max_length=200)),
                ('college', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('contact_at', models.TextField(default='', max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultant_profile',
            },
        ),
    ]
