# Generated by Django 4.2.2 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_alter_consulting_final_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulting',
            name='final_report',
        ),
        migrations.AddField(
            model_name='consulting',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consulting',
            name='final_report_base64URL',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consulting',
            name='final_report_filename',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
