# Generated by Django 4.2.2 on 2023-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_remove_consulting_final_report_consulting_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
