# Generated by Django 4.2.2 on 2023-06-27 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_consultantprofile_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('career', models.TextField(blank=True, default='', max_length=50)),
                ('menu', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=20)),
                ('area', models.CharField(blank=True, default='', max_length=20)),
                ('monthly_avg_rev', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('fee', models.IntegerField(blank=True, default=0)),
                ('content', models.TextField(blank=True)),
                ('consult_tags', models.ManyToManyField(blank=True, related_name='consultant', to='account.tag')),
                ('rest_tags', models.ManyToManyField(blank=True, related_name='restaurant', to='account.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.TextField(blank=True, default='')),
                ('req', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matching.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
