# Generated by Django 4.2.2 on 2023-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='area',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='menu',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
