# Generated by Django 4.2.2 on 2023-07-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_request_area_alter_request_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='age',
        ),
        migrations.RemoveField(
            model_name='request',
            name='area',
        ),
        migrations.RemoveField(
            model_name='request',
            name='career',
        ),
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.RemoveField(
            model_name='request',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
