# Generated by Django 4.2.2 on 2023-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_remove_request_age_remove_request_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
